on: push
jobs:
   my_initial_job:
      name: My first job
      runs-on: newrunner
      steps:
      - name: Install Dependencies
        run: echo Hello Vivek!
jobs:
   my_second_job:
      name: My second job
      runs-on: newrunner
      steps:
      - name: print
        run: echo Hello Sarthak!
     
