on: push
jobs:
   my_initial_job:
      name: My first job
      runs-on: newrunner
      steps:
      - name: Install Dependencies
        run: echo Hello Vivek!

      - name: Checkout
        uses: actions/checkout@v6.0.1

   
   
   
   
   
          
        
   
   
     
