on: push
jobs:
   my_initial_job:
      name: My first job
      runs-on: newrunner
      steps:
      - name: Install Dependencies
        run: echo Hello Vivek!
      - name: second task
        run: echo Hello Sarthak!      
